### ISSUE TITLE
User Profile Menu

### ISSUE THREAD

**Issue by iohl** [variocube/app-ui#7]
## Summary

Multiple variocube applications are missing one or more views of user profile. Thing likes changing password, view and update profile should be generic and included in the package.

### Current Behaviour

Partially implemented across multiple applications in many ways possible.

### Desired Behaviour

On the top navigation, add a user profile avatar item with drop down to access:

 - View user profile
 - Change password
 - Dark mode switcher
 - Logout

Show and hide the menu options depending on the handlers which are provided.

Support an optional image URL to support an avatar image if we have on e.g. from the IdP.

## Tasks

 - [ ] User Profile menu
 - [ ] Use for rental
 - [ ] Use for logistics
